---
date: 2018-04-29T22:00:45+09:00

title: "Writing about Alopecia Universalis"
showonlyimage: true
draft: false
weight: 0
type: "post"

description: "A short essay about my experience with Alopecia"
categories: ["memos"]
---
  April 29, 2018
<br>  
  
During my college years, I submitted a short essay for <a href="https://thisibelieve.org/">This I Believe</a>, a National Public Radio program, with help from my sister and my teacher, Vanessa Conte. While it was not chosen to be on the program, I always wanted to share with someone my experience with Alopecia and how I had reconciled with it.

In the beginning, writing was a painful process. As I wrote this essay, I found that I was hiding a lot of my feelings towards Alopecia. I was trying to find where I come from, and I questioned my existence as a person. Then, as I write, I realized that all people have the same core essence as a human being and by writing these thoughts down I could go back to the turning point of my past that was difficult for me to look back at. At the end of the writing process, I was gaining more courage to appreciate my identity. 

It was probably during the first month after our family had moved to Japan that I found a bald spot on my head. One night, I looked into the mirror placed on the dining room table and noticed a change. As I combed through my hair with my hands, it began to fall out. My eyelashes and eyebrows began to fell out as well as I traced along them with my fingers. I was eventually diagnosed with Alopecia Universalis, a rare disease that caused me to lose all my hair. I was five years old.

Rough kids at the local school would throw rocks at me because I looked different. I was an easy target because most schools in Japan taught the importance of uniformity 'being the same.' As a result, I started to wear a large cap to conceal my bald head wherever I go, trying to hide my appearance and identity.

My traumatic experience of being bald changed when my English teacher introduced me to the work of, Agnes Martin, a minimalist painter. She showed me a book called <i>Writings</i>. It was a collection of essays and paintings Martin had done late in her career. In her book, there are just pictures that consisted of consecutive lines and subdued colors. But It brought to me such honest and kind sensations that it felt like I was discharged from the doubt about whether I was living true to myself. 

The paintings allowed me to face something that had been difficult to confront since I was five, the fear of transformation. It was then that I started to build the confidence within to accept myself as someone who looked different. Thus, I slowly began to change my perception towards my appearance with Alopecia.

Not long after I had been introduced to the work of Agnes Martin, I went outside to take a walk one morning but without the hat that I had always worn. My bald head shivered in the cool air, but I felt a peace unlike anything I have ever felt before. This was the first time in ten years that I had walked outside without the hat that I had put on to hide myself. When I came back home from the walk, I grabbed my hat still in my room and threw it away. I had finally accepted the uniqueness of my appearance. The cap, once a protection of my identity, became a disguise I no longer wanted.

I think this experience has taught me how to embrace reality and be true to myself. I was terrified of my transformation at the beginning, but I found a way to make peace with my difference by knowing who I was at the core. It is still difficult for me to accept when people judge me by my facades, but I have learned to believe I can change the way I see myself in an optimistic light.

<br><br>

  
  