---
date: "2017-07-17"
title: "R言語 リスト - R Lists"
author: "斉藤ジョー"
showonlyimage: false
draft: false
image: ""
image2: "bootcamp/img/cover.jpg"
weight: 0
type: ""
description: "R言語のチュートリアル Part 9: リストの扱い方について"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      tidy.opts = list(width.cutoff = 60),
                      tidy = TRUE, 
                      out.width = '95%')
```

```{r, include = FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

<div class="video-container">
<iframe class="center_iframe" width="560" height="315" src="https://youtube.com/embed/GfT4kQX8Y0o" frameborder="0" allowfullscreen></iframe>
</div>


### リストの作成
```{r}
MyList <- list(1:5, c("dog", "cat", "bee"), c(TRUE, FALSE))
MyList
str(MyList)

a <- 1:3
b <- c("dog", "cat", NA)
c <- c(TRUE, TRUE, FALSE)
d <- data.frame(a, b, c)
MyList2 <- list(a, b, c, d)
MyList2
str(MyList2)
```

### リストの名前
```{r}
names(MyList2)
MyList2 <- list(
  first = a,
  second = b,
  third = c,
  forth = d
)
names(MyList2) <- c("first", "second", "third", "forth")
str(MyList2)
MyList2
```

###　リストの成分へアクセス
```{r}
MyList2$first
MyList2$second
MyList2[[1]]
MyList2[[2]]
MyList2[["first"]]
MyList2[["second"]]

MyList2$first[2]
MyList2[[2]][2:3]
MyList2[["second"]][c(1, 2)]

MyList2$first[2] <- 99
```

### リストに新しい成分を加える
```{r}
MyList2[[5]] <- 1:10
```

### リストの成分削除
```{r}
MyList2[[5]] <- NULL
```