---
date: "2017-07-17"
title: "R言語 行列 - R Matrices"
author: "斉藤ジョー"
showonlyimage: false
draft: false
image: ""
image2: "bootcamp/img/cover.jpg"
weight: 0
type: ""
description: "R言語のチュートリアル Part 7: 行列の作成と操作の方法について"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      tidy.opts = list(width.cutoff = 60),
                      tidy = TRUE, 
                      out.width = '95%')
```

```{r, include = FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```



<div class="video-container">
<iframe class="center_iframe" width="560" height="315" src="" frameborder="0" allowfullscreen></iframe>
</div>

行列に関する Tips 大全 (http://www.okadajp.org/RWiki/?%E8%A1%8C%E5%88%97Tips%E5%A4%A7%E5%85%A80

matrix: 行列  
row: 行  
column: 列  

### 行列
```{r}
m1 <- matrix(1:10, nrow = 2)
m1
```

### チェック
```{r}
length(m1)  #行列の要素の数を調べる
nrow(m1)  #行
ncol(m1)  #列
dim(m1)  #nxm

m2 <- matrix(1:10, nrow = 2, byrow = TRUE)
m2
m3 <- matrix(1:12,　nrow = 3,　ncol = 4,　byrow = TRUE)
m3
m4 <- matrix(c(1, 0, 0, 1),　 nrow = 2,　ncol = 2,　byrow = TRUE)
m4
```

### 索引: オブジェクト名[row,column]
```{r}
m3
m3[2, 3]
m3[3, ]
m3[, 3]
m3[2:3, ]　　
m3[, 2:3]
m3[, c(2, 4)]
m3[c(1, 2), c(3, 4)]
```

### 値を上書き
```{r}
m3
m3[3, 4] <- 0
m3
```

### 名称を付ける
```{r}
m5 <- matrix(1:4,　nrow = 2,　ncol = 2,　byrow = TRUE)
m5
rownames(m5) <- c("1st", "2nd")
colnames(m5) <- c("first", "second")
m5

rownames(m5) <- letters[1:2]　#a,b,c,...
colnames(m5) <- LETTERS[1:2]  #A,B,C,...
m5
```

### 演算 pt1
```{r}
m5 + 2
m5 - 2
m5 / 2
m5 * 2
```

### 演算 pt2
```{r}
m6 <- matrix(c(2,3,4,5), nrow = 2, ncol = 2)
m5
m6
m5 + m6
m5 - m6
m5 / m6
m5 * m6 #行列の各要素の積
m5 %*% m6 #行列の積
```

### 転置行列: 行と列の入れ替え
```{r}
m6
m7 <- t(m6)
m7
```

### 対角行列
```{r}
m8 <- diag(nrow = 2, ncol = 2)
m8
m9 <- diag(c(4, 3, 2, 1), nrow = 4, ncol = 4)
m9
```

### 逆行列
```{r}
m6
solve(m6)
m6 %*% solve(m6) #単位行列
```

### 行列式
```{r}
det(m6)
```


