---
date: "2017-07-17"
title: "R言語 NA 欠損値 - R Missing Data"
author: "斉藤ジョー"
showonlyimage: false
draft: false
image: ""
image2: "bootcamp/img/cover.jpg"
weight: 0
type: ""
description: "R言語のチュートリアル Part 6: 欠損値の扱い方について"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      tidy.opts = list(width.cutoff = 60),
                      tidy = TRUE, 
                      out.width = '95%')
```

```{r, include = FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

<div class="video-container">
<iframe class="center_iframe" width="560" height="315" src="" frameborder="0" allowfullscreen></iframe>
</div>

### ベクトル
```{r}
x <- NA
num <- c(1, 2, 3, NA)
str <- c("dog", "cat", NA, "bee")
logi <- c(TRUE, NA, FALSE, TRUE)
```

### データのタイプ
```{r}
mode(num)
mode(str)
mode(logi)
```

### NA(欠損値)の検出
```{r}
is.na(num)  #または!is.na(num)
is.na(str)
is.na(logi)
```

### NAのインデックス:
```{r}
which(is.na(num))  #which()でTRUEのインデックスを検出
which(is.na(str))
which(is.na(logi))
```

### ベクトルからNAを取り除く
```{r}
num <- num[!is.na(num)]
```